[project]
name = "highperfpython"
version = "0.1.0"
description = "Method for evaluating performances in Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "maturin>=1.8.3",
    "ruff>=0.11.7",
]
